### ISSUE TITLE
Rebase feature-collision-check branch with master

### ISSUE THREAD

**Issue by ksatyaki** [OrebroUniversity/hiqp#28]
Need to rebase feature collision check branch with master.

**Comment by neckutrek** [comment]
The feature collision check branch deviates a bit with master when it comes to how the geometric primitive map is used. I think that the geometric primitives are extended with type identification which is used to downcast to subclasses. This should be corrected if rebased onto master so that hiqp_core can be left unaltered if possible.
I wrote about this issue on the wiki.

**Comment by ksatyaki** [comment]
The GeometricPrimitiveMap seems only to be outdated. Not different.

**Comment by neckutrek** [comment]
Ok, then perhaps check the primitives namespace. I might be wrong too, if
there are no changes everythings fine :)

**Comment by ksatyaki** [comment]
It has diverged quite a bit. Manual merge of features is required. Git
tends to screw it up.
